function [m,n,A] = statisticalWBfit(Imef,Ihpf,Ilpf,Ivf,z,isplot)
    

    for i=1:3 %each color independetly
        mlb=-3; mub=3; nlb= mean(Ilpf,'all')/2; nub=mean(Ilpf,'all')*2;
        %bounderies
        lb=[mlb nlb  0.5 0.5];% mlb nlb mlb nlb];
        ub=[mub nub  10   2 ];% mub nub mub nub];
        x0=[  0 nlb*2 1.5 1 ];% 0   nlb*2 0 nlb*2];
        %   Binf      betaB  log(JD)     betaD(1)  DC   betaD(2 3 4)
        
        fun = @(a) [...%(Imf(:,1)+Imf(:,1)+Imf(:,1)-3*(a(1)*z+a(2))),...
%                     3*(Imef(:,1))*a(3)-(Imef(:,2))*a(4),...
%                     3*(Imef(:,1))*a(3)-(Imef(:,3)),...
%                     (Ihpf(:,1))*a(3)-(Ihpf(:,2))*a(4),...
%                     (Ihpf(:,1))*a(3)-(Ihpf(:,3)),...
%                     2*(Ilpf(:,1))*a(3)-(Ilpf(:,2))*a(4),...
%                     2*(Ilpf(:,1))*a(3)-(Ilpf(:,3)),...
                    ...%(Imf(:,2)-(a(1)*z+a(2)))*a(4)-(Imf(:,3)-(a(1)*z+a(2))),...
                    (Ilpf(:,1)-(a(1)*z+a(2)))*a(3)-(Ilpf(:,2)-(a(1)*z+a(2)))*a(4),...
                    (Ilpf(:,1)-(a(1)*z+a(2)))*a(3)-(Ilpf(:,3)-(a(1)*z+a(2))),...
                    0.2 .* sqrt(abs((Ivf(:,1).*(a(3).^2)-Ivf(:,2).*(a(4).^2)))),...
                    0.2 .* sqrt(abs((Ivf(:,1).*(a(3).^2)-Ivf(:,3)))),...
                    0.2 .* sqrt(abs((Ivf(:,2).*(a(4).^2)-Ivf(:,3))))...
                    ...%(a(1)-a(5)),a(5)-a(7),a(1)-a(7),...
                    ...%a(2)-a(6),a(6)-a(8),a(2)-a(8),...
                    ];
%                     (Imef(:,1)-(a(1)*z+a(2)))*a(3)-(Imef(:,2)-(a(1)*z+a(2)))*a(4),...
%                     (Imef(:,1)-(a(1)*z+a(2)))*a(3)-(Imef(:,3)-(a(1)*z+a(2))),...
%                     (Ihpf(:,1)-(a(1)*z+a(2)))*a(3)-(Ihpf(:,2)-(a(1)*z+a(2)))*a(4),...
%                     (Ihpf(:,1)-(a(1)*z+a(2)))*a(3)-(Ihpf(:,3)-(a(1)*z+a(2))),...

        x = lsqnonlin(fun,x0,lb,ub);
    end
    m=[x(1)];% x(5) x(7)];
    n=[x(2)];% x(6) x(8)]; 
    A=[x(3) x(4) 1];
    
    if isplot
        for i=1:3
        rgb=['#D95319';'#77AC30';'#0072BD'];

        figure(5)

        plot(z,(Imef(:,i)-(m*z+n))*A(i)+(m*z+n),'Marker','.','Color',rgb(i,:));
        hold on;
        plot(z,Imef(:,i),'--','Color',rgb(i,:));
        
        grid minor;
        title('Statistical White Balance - Maximal Intensity');
        
        if i==3
            plot(z,m*z+n,'--k');
            %plot(z,(ones(size(z))*n),'.-k');
            legend('a_r(E[I_r|z]-h(z))+h(z)','E[I_r|z]',...
                   'a_g(E[I_g|z]-h(z))+h(z)','E[I_g|z]',...
                   '(E[I_b|z]-h(z))+h(z)','E[I_b|z]',...
                    'h_{affine}(z)',...
                    'Location','southwest','NumColumns',4);
        end
        ylabel('Maximal Intensity'); xlabel('z distance [m]');
        
        figure(6)
        plot(z,Ivf(:,i)*A(i),'Marker','.','Color',rgb(i,:));
        hold on;
        plot(z,Ivf(:,i),'--','Color',rgb(i,:));
        grid minor;
        if i==3
            legend('a^2_r Var[I_r|z]','Var[I_r|z]',...
                   'a^2_g Var[I_g|z]','Var[I_g|z]',...
                   'Var[I_b|z]','Var[I_b|z]',...
                   'Location','northwest','NumColumns',3);
        end
        title('Statistical White Balance - Color Variance');
        %legend('minus BSmodel, times exp','minus empBS, times exp','minus BSmodel, times ratio','pre-fix'); %,'I_{mbsr}.*(I_{ebsr}^{(1)}/I_{ebsr}'
        %legend('fixed','original'); %,'I_{mbsr}.*(I_{ebsr}^{(1)}/I_{ebsr}'
        ylabel('Variance'); xlabel('z distance [m]');
        
        end
    end
    
end